#!/bin/sh
#
# Add lv2 designation param feature to envelope parameters in .ttl file
# generated by DPF.
#
# Usage:
# sh add-designation-param.sh <file.ttl>
#
# Example:
# sh add-designation-param.sh MiMi-d.ttl
#
TTL_FILE=$1

# add_prefix_url prefix-name url sedfile
add_prefix_url() {
  param="$1:"
  url="<$2>"
  line="@prefix $param $url ."
  echo Add $line at first empty line
  # Replace every / with \/ so we can use it as a replace string with sed
  line=$(echo $line | sed 's/\//\\\//g')
  echo "0,/^\$/s/^\$/$line\\\n/" >> $3
}

# add_designation_param param-name lv2-designation-param-name sedfile
add_designation_param() {
  param_with_quotes="\"$1\""
  lv2_feature="lv2:designation param:$2"
  echo Add $lv2_feature after parameter $1
  echo "/$param_with_quotes/a\\\\\t$lv2_feature ;" >> $3
}

# add_designation_params_if file-name
add_designation_params_if() {
  # We assume that if the prefix url surrounded by < > is present in the file,
  # then all the parameters are present too.
  # If so, we have nothing to do, so get outta here
  prefix_url='http://lv2plug.in/ns/ext/parameters#'
  grep "<$prefix_url>" $1 > /dev/null && return

  # Gather up all sed commands in $sedfile then execute them all at once
  sedfile=/tmp/sedfile-$$

  add_prefix_url param $prefix_url $sedfile

  add_designation_param attack attack $sedfile
  add_designation_param hold hold $sedfile
  add_designation_param decay decay $sedfile
  add_designation_param sustain sustain $sedfile
  add_designation_param sustaintime fade $sedfile
  add_designation_param release release $sedfile

  add_designation_param filterattack attack $sedfile
  add_designation_param filterhold hold $sedfile
  add_designation_param filterdecay decay $sedfile
  add_designation_param filtersustain sustain $sedfile
  add_designation_param filtersustaintime fade $sedfile
  add_designation_param filterrelease release $sedfile

  add_designation_param cutoff cutoffFrequency $sedfile
  add_designation_param resonance resonance $sedfile

  sed -i -f $sedfile $1
  rm -f $sedfile
}

add_designation_params_if $TTL_FILE
